services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 8G

  middle_layer:
    build:
      context: .
      dockerfile: Dockerfile.middle
    container_name: middle_layer
    volumes:
      - ./chat_pdf:/app
      - pdf_storage:/app/uploads  # Volume for PDF storage
      - vector_storage:/app/vector_db  # Volume for RAG vector data
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 4G

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: streamlit_app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - ollama
      - middle_layer
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2G

  user_chat:
    build:
      context: .
      dockerfile: Dockerfile.user_chat
    container_name: user_chat
    volumes:
      - .:/app
    ports:
      - "8502:8502"
    depends_on:
      - middle_layer
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2G

volumes:
  pdf_storage:  # Volume for PDF storage
  vector_storage:  # Volume for RAG vector data
